services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      LOGGER_DEBUG: true
      LOGGER_PRETTY: true
      PORT: ":8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: apifoo
      POSTGRES_PASSWORD: apifoo
      POSTGRES_DB: apifoo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}