services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      LOGGER_DEBUG: true
      LOGGER_PRETTY: true
      POSTGRES_USER: apifoo
      POSTGRES_PASSWORD: apifoo
      POSTGRES_HOST: postgres
      POSTGRES_DB: development
      PORT: ":8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: apifoo
      POSTGRES_PASSWORD: apifoo
      POSTGRES_DB: development
    ports:
      - "5432:5432"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: {}